---
- name: Copy container logs
  shell: |
    mkdir -p {{ results_dir ../../data/logs
    docker logs ncs-controller > {{ results_dir ../../data/logs/controller.log 2>&1
    docker logs ncs-agents > {{ results_dir ../../data/logs/agents.log 2>&1
    docker logs ncs-plant-pendulum > {{ results_dir ../../data/logs/plant-pendulum.log 2>&1 || echo "Pendulum plant not available"
    docker logs ncs-plant-unstable > {{ results_dir ../../data/logs/plant-unstable.log 2>&1 || echo "Unstable plant not available"

- name: Collect final system state
  uri:
    url: "http://localhost:5001/status"
    method: GET
  register: final_controller_state

- name: Save final controller state
  copy:
    content: "{{ final_controller_state.json | to_nice_json }}"
    dest: "{{ results_dir }}/final_controller_state.json"

- name: Collect final agent metrics
  uri:
    url: "http://localhost:5002/status"
    method: GET
  register: final_agent_state

- name: Save final agent state
  copy:
    content: "{{ final_agent_state.json | to_nice_json }}"
    dest: "{{ results_dir }}/final_agent_state.json"

- name: Generate experiment summary
  copy:
    content: |
      # NCS Experiment Summary
      
      **Experiment Type:** {{ experiment_type }}
      **Start Time:** {{ ansible_date_time.iso8601 }}
      **Duration:** {{ experiment_duration | default(300) }} seconds
      
      ## Final Metrics
      
      ### Controller
      - Active: {{ final_controller_state.json.active }}
      - Control Type: {{ final_controller_state.json.control_type }}
      - Sampling Period: {{ final_controller_state.json.sampling_period }}s
      - Control Cost: {{ final_controller_state.json.kpis.control_cost }}
      - Overshoot: {{ final_controller_state.json.kpis.overshoot }}
      - Settling Time: {{ final_controller_state.json.kpis.settling_time }}s
      
      ### Agent System  
      - Active Agents: {{ final_agent_state.json.active_agents }}
      - Recoveries: {{ final_agent_state.json.num_recoveries }}
      - MTTR: {{ final_agent_state.json.mttr }}s
      - Stability Margin: {{ final_agent_state.json.control_kpis.stability_margin }}
      
      ## Files Generated
      - Baseline metrics: `baseline_metrics.csv`
      - Controller logs: `logs/controller.log`
      - Agent logs: `logs/agents.log`
      - Final states: `final_*_state.json`
      
    dest: "{{ results_dir }}/experiment_summary.md"
    
- name: Display results summary
  debug:
    msg: |
      ✅ Experiment {{ experiment_type }} completed successfully!
      
      📊 Key Results:
      - MTTR: {{ final_agent_state.json.mttr }}s
      - Recoveries: {{ final_agent_state.json.num_recoveries }}
      - Control Cost: {{ final_controller_state.json.kpis.control_cost }}
      - Stability Margin: {{ final_agent_state.json.control_kpis.stability_margin }}
      
      📁 Results saved to: {{ results_dir }}
